### ISSUE TITLE
Update/restructure the FundOSS Fund/Collective

### ISSUE THREAD

**Issue by gusaus** [FUNDOSS/fundoss#47]
We need to update/restructure https://opencollective.com/fundoss so it can enable match funds for  multiple projects, categories and groups for ongoing Democratic/Quadratic Funding rounds AND provide an easy way to fund multiple collectives in a category, focus area, or even regions and cities.

### Funds for Focus areas, open source projects/ecosystems, and locations
- create projects (essentially [Funds](https://docs.opencollective.com/help/financial-contributors/organizations/funds)) for corresponding Categories/Tags on https://discover.opencollective.com/ 
- link to the projects/funds from corresponding pages on https://discover.opencollective.com/ (see https://discover.opencollective.com/foundation for an example)

#### Open Source projects/ecosystems
- [Drupal](https://discover.opencollective.com/?tag=drupal)
- [WordPress](https://discover.opencollective.com/?tag=wordpress)
- [Linux](https://discover.opencollective.com/?tag=linux)
- [Python](https://discover.opencollective.com/?tag=python)

#### Focus areas
- [Arts & Culture](https://discover.opencollective.com/?tag=arts+and+culture)
- [Civic Tech](https://discover.opencollective.com/?tag=civic+tech)
- [Climate](https://discover.opencollective.com/?tag=climate)
- [Education](https://discover.opencollective.com/?tag=education)
- [Mutual Aid](https://discover.opencollective.com/?tag=mutual+aid)
- [Open Source](https://discover.opencollective.com/?tag=open+source)
- [Publishing](https://discover.opencollective.com/?tag=publishing) 

#### Regions/Countries/Cities
- [Africa](https://discover.opencollective.com/?location=Africa&locationType=region)
- [United States](https://discover.opencollective.com/?location=US&locationType=country)
- [Los Angeles](https://discover.opencollective.com/?location=Los+Angeles&locationType=city)

### Match Funds for Democratic Funding rounds
While all of the projects/funds (in the examples above) could participate we'll need some way to isolate the match fund and specific funding round. Seems like we could do this with some combo of tiers and events?

### Todo

- [ ] Gather feedback/input from FundOSS admins/team members 
- [ ] Determine resources needed to properly set this up
- [ ] Secure resources and move forward
